[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test/foundry'
cache_path  = 'forge-cache'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[invariant]
runs = 2000
depth = 10
fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true